server:
  port: "50054"
  env: "development"

cloudinary:
  cloud_name: "your_cloud_name"
  api_key: "your_api_key"
  api_secret: "your_api_secret"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "netflix"
  sslmode: "disable"
