// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/recommendation/recommendation.proto

package recommendation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsRequest) Reset() {
	*x = GetRecommendationsRequest{}
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsRequest) ProtoMessage() {}

func (x *GetRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *GetRecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRecommendationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Recommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *Recommendation) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *Recommendation) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Recommendation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetRecommendationsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*Recommendation      `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRecommendationsResponse) Reset() {
	*x = GetRecommendationsResponse{}
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsResponse) ProtoMessage() {}

func (x *GetRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *GetRecommendationsResponse) GetRecommendations() []*Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

type GetTrendingMoviesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	TimeRange     string                 `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"` // day, week, month
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingMoviesRequest) Reset() {
	*x = GetTrendingMoviesRequest{}
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingMoviesRequest) ProtoMessage() {}

func (x *GetTrendingMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingMoviesRequest.ProtoReflect.Descriptor instead.
func (*GetTrendingMoviesRequest) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_recommendation_proto_rawDescGZIP(), []int{3}
}

func (x *GetTrendingMoviesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTrendingMoviesRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

type TrendingMovie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	ViewCount     int32                  `protobuf:"varint,2,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	TrendingScore float64                `protobuf:"fixed64,3,opt,name=trending_score,json=trendingScore,proto3" json:"trending_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingMovie) Reset() {
	*x = TrendingMovie{}
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingMovie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingMovie) ProtoMessage() {}

func (x *TrendingMovie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingMovie.ProtoReflect.Descriptor instead.
func (*TrendingMovie) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_recommendation_proto_rawDescGZIP(), []int{4}
}

func (x *TrendingMovie) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *TrendingMovie) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *TrendingMovie) GetTrendingScore() float64 {
	if x != nil {
		return x.TrendingScore
	}
	return 0
}

type GetTrendingMoviesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*TrendingMovie       `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingMoviesResponse) Reset() {
	*x = GetTrendingMoviesResponse{}
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingMoviesResponse) ProtoMessage() {}

func (x *GetTrendingMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingMoviesResponse.ProtoReflect.Descriptor instead.
func (*GetTrendingMoviesResponse) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_recommendation_proto_rawDescGZIP(), []int{5}
}

func (x *GetTrendingMoviesResponse) GetMovies() []*TrendingMovie {
	if x != nil {
		return x.Movies
	}
	return nil
}

type GetSimilarMoviesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimilarMoviesRequest) Reset() {
	*x = GetSimilarMoviesRequest{}
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimilarMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarMoviesRequest) ProtoMessage() {}

func (x *GetSimilarMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimilarMoviesRequest.ProtoReflect.Descriptor instead.
func (*GetSimilarMoviesRequest) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_recommendation_proto_rawDescGZIP(), []int{6}
}

func (x *GetSimilarMoviesRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *GetSimilarMoviesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SimilarMovie struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MovieId         string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	SimilarityScore float64                `protobuf:"fixed64,2,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SimilarMovie) Reset() {
	*x = SimilarMovie{}
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarMovie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarMovie) ProtoMessage() {}

func (x *SimilarMovie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarMovie.ProtoReflect.Descriptor instead.
func (*SimilarMovie) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_recommendation_proto_rawDescGZIP(), []int{7}
}

func (x *SimilarMovie) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *SimilarMovie) GetSimilarityScore() float64 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

type GetSimilarMoviesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*SimilarMovie        `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimilarMoviesResponse) Reset() {
	*x = GetSimilarMoviesResponse{}
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimilarMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarMoviesResponse) ProtoMessage() {}

func (x *GetSimilarMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_recommendation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimilarMoviesResponse.ProtoReflect.Descriptor instead.
func (*GetSimilarMoviesResponse) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_recommendation_proto_rawDescGZIP(), []int{8}
}

func (x *GetSimilarMoviesResponse) GetMovies() []*SimilarMovie {
	if x != nil {
		return x.Movies
	}
	return nil
}

var File_proto_recommendation_recommendation_proto protoreflect.FileDescriptor

const file_proto_recommendation_recommendation_proto_rawDesc = "" +
	"\n" +
	")proto/recommendation/recommendation.proto\x12\x0erecommendation\"J\n" +
	"\x19GetRecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"Y\n" +
	"\x0eRecommendation\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"f\n" +
	"\x1aGetRecommendationsResponse\x12H\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x1e.recommendation.RecommendationR\x0frecommendations\"O\n" +
	"\x18GetTrendingMoviesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\"p\n" +
	"\rTrendingMovie\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x12\x1d\n" +
	"\n" +
	"view_count\x18\x02 \x01(\x05R\tviewCount\x12%\n" +
	"\x0etrending_score\x18\x03 \x01(\x01R\rtrendingScore\"R\n" +
	"\x19GetTrendingMoviesResponse\x125\n" +
	"\x06movies\x18\x01 \x03(\v2\x1d.recommendation.TrendingMovieR\x06movies\"J\n" +
	"\x17GetSimilarMoviesRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"T\n" +
	"\fSimilarMovie\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x12)\n" +
	"\x10similarity_score\x18\x02 \x01(\x01R\x0fsimilarityScore\"P\n" +
	"\x18GetSimilarMoviesResponse\x124\n" +
	"\x06movies\x18\x01 \x03(\v2\x1c.recommendation.SimilarMovieR\x06movies2\xd5\x02\n" +
	"\x15RecommendationService\x12k\n" +
	"\x12GetRecommendations\x12).recommendation.GetRecommendationsRequest\x1a*.recommendation.GetRecommendationsResponse\x12h\n" +
	"\x11GetTrendingMovies\x12(.recommendation.GetTrendingMoviesRequest\x1a).recommendation.GetTrendingMoviesResponse\x12e\n" +
	"\x10GetSimilarMovies\x12'.recommendation.GetSimilarMoviesRequest\x1a(.recommendation.GetSimilarMoviesResponseB9Z7github.com/datmedevil17/micro-flex/proto/recommendationb\x06proto3"

var (
	file_proto_recommendation_recommendation_proto_rawDescOnce sync.Once
	file_proto_recommendation_recommendation_proto_rawDescData []byte
)

func file_proto_recommendation_recommendation_proto_rawDescGZIP() []byte {
	file_proto_recommendation_recommendation_proto_rawDescOnce.Do(func() {
		file_proto_recommendation_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_recommendation_recommendation_proto_rawDesc), len(file_proto_recommendation_recommendation_proto_rawDesc)))
	})
	return file_proto_recommendation_recommendation_proto_rawDescData
}

var file_proto_recommendation_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_recommendation_recommendation_proto_goTypes = []any{
	(*GetRecommendationsRequest)(nil),  // 0: recommendation.GetRecommendationsRequest
	(*Recommendation)(nil),             // 1: recommendation.Recommendation
	(*GetRecommendationsResponse)(nil), // 2: recommendation.GetRecommendationsResponse
	(*GetTrendingMoviesRequest)(nil),   // 3: recommendation.GetTrendingMoviesRequest
	(*TrendingMovie)(nil),              // 4: recommendation.TrendingMovie
	(*GetTrendingMoviesResponse)(nil),  // 5: recommendation.GetTrendingMoviesResponse
	(*GetSimilarMoviesRequest)(nil),    // 6: recommendation.GetSimilarMoviesRequest
	(*SimilarMovie)(nil),               // 7: recommendation.SimilarMovie
	(*GetSimilarMoviesResponse)(nil),   // 8: recommendation.GetSimilarMoviesResponse
}
var file_proto_recommendation_recommendation_proto_depIdxs = []int32{
	1, // 0: recommendation.GetRecommendationsResponse.recommendations:type_name -> recommendation.Recommendation
	4, // 1: recommendation.GetTrendingMoviesResponse.movies:type_name -> recommendation.TrendingMovie
	7, // 2: recommendation.GetSimilarMoviesResponse.movies:type_name -> recommendation.SimilarMovie
	0, // 3: recommendation.RecommendationService.GetRecommendations:input_type -> recommendation.GetRecommendationsRequest
	3, // 4: recommendation.RecommendationService.GetTrendingMovies:input_type -> recommendation.GetTrendingMoviesRequest
	6, // 5: recommendation.RecommendationService.GetSimilarMovies:input_type -> recommendation.GetSimilarMoviesRequest
	2, // 6: recommendation.RecommendationService.GetRecommendations:output_type -> recommendation.GetRecommendationsResponse
	5, // 7: recommendation.RecommendationService.GetTrendingMovies:output_type -> recommendation.GetTrendingMoviesResponse
	8, // 8: recommendation.RecommendationService.GetSimilarMovies:output_type -> recommendation.GetSimilarMoviesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_recommendation_recommendation_proto_init() }
func file_proto_recommendation_recommendation_proto_init() {
	if File_proto_recommendation_recommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_recommendation_recommendation_proto_rawDesc), len(file_proto_recommendation_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_recommendation_recommendation_proto_goTypes,
		DependencyIndexes: file_proto_recommendation_recommendation_proto_depIdxs,
		MessageInfos:      file_proto_recommendation_recommendation_proto_msgTypes,
	}.Build()
	File_proto_recommendation_recommendation_proto = out.File
	file_proto_recommendation_recommendation_proto_goTypes = nil
	file_proto_recommendation_recommendation_proto_depIdxs = nil
}
