syntax = "proto3";

package movie;

option go_package = "proto/movie";

service MovieService {
  rpc CreateMovie(CreateMovieRequest) returns (CreateMovieResponse);
  rpc GetMovie(GetMovieRequest) returns (GetMovieResponse);
  rpc ListMovies(ListMoviesRequest) returns (ListMoviesResponse);
}

message CreateMovieRequest {
  string title = 1;
  string description = 2;
  string director = 3;
}

message CreateMovieResponse { string id = 1; }

message GetMovieRequest { string id = 1; }

message GetMovieResponse {
  string id = 1;
  string title = 2;
  string description = 3;
  string director = 4;
}

message ListMoviesRequest {
  int32 page = 1;
  int32 page_size = 2;
}

message ListMoviesResponse { repeated GetMovieResponse movies = 1; }
