// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/streaming/streaming.proto

package streaming

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStreamingURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       string                 `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Quality       int32                  `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"` // 360, 480, 720, 1080
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamingURLRequest) Reset() {
	*x = GetStreamingURLRequest{}
	mi := &file_proto_streaming_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamingURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamingURLRequest) ProtoMessage() {}

func (x *GetStreamingURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamingURLRequest.ProtoReflect.Descriptor instead.
func (*GetStreamingURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_streaming_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *GetStreamingURLRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

func (x *GetStreamingURLRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetStreamingURLRequest) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

type GetStreamingURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamingUrl  string                 `protobuf:"bytes,1,opt,name=streaming_url,json=streamingUrl,proto3" json:"streaming_url,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"` // seconds
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamingURLResponse) Reset() {
	*x = GetStreamingURLResponse{}
	mi := &file_proto_streaming_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamingURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamingURLResponse) ProtoMessage() {}

func (x *GetStreamingURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamingURLResponse.ProtoReflect.Descriptor instead.
func (*GetStreamingURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_streaming_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *GetStreamingURLResponse) GetStreamingUrl() string {
	if x != nil {
		return x.StreamingUrl
	}
	return ""
}

func (x *GetStreamingURLResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *GetStreamingURLResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ValidateStreamAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MovieId       string                 `protobuf:"bytes,2,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateStreamAccessRequest) Reset() {
	*x = ValidateStreamAccessRequest{}
	mi := &file_proto_streaming_streaming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateStreamAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateStreamAccessRequest) ProtoMessage() {}

func (x *ValidateStreamAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_streaming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateStreamAccessRequest.ProtoReflect.Descriptor instead.
func (*ValidateStreamAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_streaming_streaming_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateStreamAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateStreamAccessRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type ValidateStreamAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasAccess     bool                   `protobuf:"varint,1,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateStreamAccessResponse) Reset() {
	*x = ValidateStreamAccessResponse{}
	mi := &file_proto_streaming_streaming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateStreamAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateStreamAccessResponse) ProtoMessage() {}

func (x *ValidateStreamAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streaming_streaming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateStreamAccessResponse.ProtoReflect.Descriptor instead.
func (*ValidateStreamAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_streaming_streaming_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateStreamAccessResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

func (x *ValidateStreamAccessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_streaming_streaming_proto protoreflect.FileDescriptor

const file_proto_streaming_streaming_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/streaming/streaming.proto\x12\tstreaming\"f\n" +
	"\x16GetStreamingURLRequest\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\tR\amovieId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\aquality\x18\x03 \x01(\x05R\aquality\"w\n" +
	"\x17GetStreamingURLResponse\x12#\n" +
	"\rstreaming_url\x18\x01 \x01(\tR\fstreamingUrl\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x05R\texpiresIn\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"Q\n" +
	"\x1bValidateStreamAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmovie_id\x18\x02 \x01(\tR\amovieId\"W\n" +
	"\x1cValidateStreamAccessResponse\x12\x1d\n" +
	"\n" +
	"has_access\x18\x01 \x01(\bR\thasAccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd5\x01\n" +
	"\x10StreamingService\x12X\n" +
	"\x0fGetStreamingURL\x12!.streaming.GetStreamingURLRequest\x1a\".streaming.GetStreamingURLResponse\x12g\n" +
	"\x14ValidateStreamAccess\x12&.streaming.ValidateStreamAccessRequest\x1a'.streaming.ValidateStreamAccessResponseB4Z2github.com/datmedevil17/micro-flex/proto/streamingb\x06proto3"

var (
	file_proto_streaming_streaming_proto_rawDescOnce sync.Once
	file_proto_streaming_streaming_proto_rawDescData []byte
)

func file_proto_streaming_streaming_proto_rawDescGZIP() []byte {
	file_proto_streaming_streaming_proto_rawDescOnce.Do(func() {
		file_proto_streaming_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_streaming_streaming_proto_rawDesc), len(file_proto_streaming_streaming_proto_rawDesc)))
	})
	return file_proto_streaming_streaming_proto_rawDescData
}

var file_proto_streaming_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_streaming_streaming_proto_goTypes = []any{
	(*GetStreamingURLRequest)(nil),       // 0: streaming.GetStreamingURLRequest
	(*GetStreamingURLResponse)(nil),      // 1: streaming.GetStreamingURLResponse
	(*ValidateStreamAccessRequest)(nil),  // 2: streaming.ValidateStreamAccessRequest
	(*ValidateStreamAccessResponse)(nil), // 3: streaming.ValidateStreamAccessResponse
}
var file_proto_streaming_streaming_proto_depIdxs = []int32{
	0, // 0: streaming.StreamingService.GetStreamingURL:input_type -> streaming.GetStreamingURLRequest
	2, // 1: streaming.StreamingService.ValidateStreamAccess:input_type -> streaming.ValidateStreamAccessRequest
	1, // 2: streaming.StreamingService.GetStreamingURL:output_type -> streaming.GetStreamingURLResponse
	3, // 3: streaming.StreamingService.ValidateStreamAccess:output_type -> streaming.ValidateStreamAccessResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_streaming_streaming_proto_init() }
func file_proto_streaming_streaming_proto_init() {
	if File_proto_streaming_streaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_streaming_streaming_proto_rawDesc), len(file_proto_streaming_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_streaming_streaming_proto_goTypes,
		DependencyIndexes: file_proto_streaming_streaming_proto_depIdxs,
		MessageInfos:      file_proto_streaming_streaming_proto_msgTypes,
	}.Build()
	File_proto_streaming_streaming_proto = out.File
	file_proto_streaming_streaming_proto_goTypes = nil
	file_proto_streaming_streaming_proto_depIdxs = nil
}
