// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/upload/upload.proto

package upload

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MovieId       string                 `protobuf:"bytes,3,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoRequest) Reset() {
	*x = UploadVideoRequest{}
	mi := &file_proto_upload_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoRequest) ProtoMessage() {}

func (x *UploadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upload_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoRequest.ProtoReflect.Descriptor instead.
func (*UploadVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_upload_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadVideoRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UploadVideoRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadVideoRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type UploadVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	PublicId      string                 `protobuf:"bytes,2,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoResponse) Reset() {
	*x = UploadVideoResponse{}
	mi := &file_proto_upload_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoResponse) ProtoMessage() {}

func (x *UploadVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upload_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoResponse.ProtoReflect.Descriptor instead.
func (*UploadVideoResponse) Descriptor() ([]byte, []int) {
	return file_proto_upload_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadVideoResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadVideoResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *UploadVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UploadThumbnailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MovieId       string                 `protobuf:"bytes,3,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadThumbnailRequest) Reset() {
	*x = UploadThumbnailRequest{}
	mi := &file_proto_upload_upload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadThumbnailRequest) ProtoMessage() {}

func (x *UploadThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upload_upload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadThumbnailRequest.ProtoReflect.Descriptor instead.
func (*UploadThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_proto_upload_upload_proto_rawDescGZIP(), []int{2}
}

func (x *UploadThumbnailRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UploadThumbnailRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadThumbnailRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type UploadThumbnailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	PublicId      string                 `protobuf:"bytes,2,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadThumbnailResponse) Reset() {
	*x = UploadThumbnailResponse{}
	mi := &file_proto_upload_upload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadThumbnailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadThumbnailResponse) ProtoMessage() {}

func (x *UploadThumbnailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upload_upload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadThumbnailResponse.ProtoReflect.Descriptor instead.
func (*UploadThumbnailResponse) Descriptor() ([]byte, []int) {
	return file_proto_upload_upload_proto_rawDescGZIP(), []int{3}
}

func (x *UploadThumbnailResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadThumbnailResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *UploadThumbnailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UploadAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarRequest) Reset() {
	*x = UploadAvatarRequest{}
	mi := &file_proto_upload_upload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarRequest) ProtoMessage() {}

func (x *UploadAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upload_upload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarRequest.ProtoReflect.Descriptor instead.
func (*UploadAvatarRequest) Descriptor() ([]byte, []int) {
	return file_proto_upload_upload_proto_rawDescGZIP(), []int{4}
}

func (x *UploadAvatarRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UploadAvatarRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadAvatarRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UploadAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	PublicId      string                 `protobuf:"bytes,2,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarResponse) Reset() {
	*x = UploadAvatarResponse{}
	mi := &file_proto_upload_upload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarResponse) ProtoMessage() {}

func (x *UploadAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upload_upload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarResponse.ProtoReflect.Descriptor instead.
func (*UploadAvatarResponse) Descriptor() ([]byte, []int) {
	return file_proto_upload_upload_proto_rawDescGZIP(), []int{5}
}

func (x *UploadAvatarResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadAvatarResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *UploadAvatarResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // video, image, raw
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_proto_upload_upload_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upload_upload_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_upload_upload_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFileRequest) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *DeleteFileRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_proto_upload_upload_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upload_upload_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_upload_upload_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_upload_upload_proto protoreflect.FileDescriptor

const file_proto_upload_upload_proto_rawDesc = "" +
	"\n" +
	"\x19proto/upload/upload.proto\x12\x06upload\"i\n" +
	"\x12UploadVideoRequest\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x19\n" +
	"\bmovie_id\x18\x03 \x01(\tR\amovieId\"^\n" +
	"\x13UploadVideoResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\tpublic_id\x18\x02 \x01(\tR\bpublicId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"m\n" +
	"\x16UploadThumbnailRequest\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x19\n" +
	"\bmovie_id\x18\x03 \x01(\tR\amovieId\"b\n" +
	"\x17UploadThumbnailResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\tpublic_id\x18\x02 \x01(\tR\bpublicId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"h\n" +
	"\x13UploadAvatarRequest\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"_\n" +
	"\x14UploadAvatarResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\tpublic_id\x18\x02 \x01(\tR\bpublicId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"U\n" +
	"\x11DeleteFileRequest\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\".\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xbb\x02\n" +
	"\rUploadService\x12F\n" +
	"\vUploadVideo\x12\x1a.upload.UploadVideoRequest\x1a\x1b.upload.UploadVideoResponse\x12R\n" +
	"\x0fUploadThumbnail\x12\x1e.upload.UploadThumbnailRequest\x1a\x1f.upload.UploadThumbnailResponse\x12I\n" +
	"\fUploadAvatar\x12\x1b.upload.UploadAvatarRequest\x1a\x1c.upload.UploadAvatarResponse\x12C\n" +
	"\n" +
	"DeleteFile\x12\x19.upload.DeleteFileRequest\x1a\x1a.upload.DeleteFileResponseB1Z/github.com/datmedevil17/micro-flex/proto/uploadb\x06proto3"

var (
	file_proto_upload_upload_proto_rawDescOnce sync.Once
	file_proto_upload_upload_proto_rawDescData []byte
)

func file_proto_upload_upload_proto_rawDescGZIP() []byte {
	file_proto_upload_upload_proto_rawDescOnce.Do(func() {
		file_proto_upload_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_upload_upload_proto_rawDesc), len(file_proto_upload_upload_proto_rawDesc)))
	})
	return file_proto_upload_upload_proto_rawDescData
}

var file_proto_upload_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_upload_upload_proto_goTypes = []any{
	(*UploadVideoRequest)(nil),      // 0: upload.UploadVideoRequest
	(*UploadVideoResponse)(nil),     // 1: upload.UploadVideoResponse
	(*UploadThumbnailRequest)(nil),  // 2: upload.UploadThumbnailRequest
	(*UploadThumbnailResponse)(nil), // 3: upload.UploadThumbnailResponse
	(*UploadAvatarRequest)(nil),     // 4: upload.UploadAvatarRequest
	(*UploadAvatarResponse)(nil),    // 5: upload.UploadAvatarResponse
	(*DeleteFileRequest)(nil),       // 6: upload.DeleteFileRequest
	(*DeleteFileResponse)(nil),      // 7: upload.DeleteFileResponse
}
var file_proto_upload_upload_proto_depIdxs = []int32{
	0, // 0: upload.UploadService.UploadVideo:input_type -> upload.UploadVideoRequest
	2, // 1: upload.UploadService.UploadThumbnail:input_type -> upload.UploadThumbnailRequest
	4, // 2: upload.UploadService.UploadAvatar:input_type -> upload.UploadAvatarRequest
	6, // 3: upload.UploadService.DeleteFile:input_type -> upload.DeleteFileRequest
	1, // 4: upload.UploadService.UploadVideo:output_type -> upload.UploadVideoResponse
	3, // 5: upload.UploadService.UploadThumbnail:output_type -> upload.UploadThumbnailResponse
	5, // 6: upload.UploadService.UploadAvatar:output_type -> upload.UploadAvatarResponse
	7, // 7: upload.UploadService.DeleteFile:output_type -> upload.DeleteFileResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_upload_upload_proto_init() }
func file_proto_upload_upload_proto_init() {
	if File_proto_upload_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_upload_upload_proto_rawDesc), len(file_proto_upload_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_upload_upload_proto_goTypes,
		DependencyIndexes: file_proto_upload_upload_proto_depIdxs,
		MessageInfos:      file_proto_upload_upload_proto_msgTypes,
	}.Build()
	File_proto_upload_upload_proto = out.File
	file_proto_upload_upload_proto_goTypes = nil
	file_proto_upload_upload_proto_depIdxs = nil
}
